name: alsana_alharfiyin
description: "تطبيق الصانع الحرفي - منصة ربط الحرفيين بأصحاب المشاريع في العالم العربي"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core - Compatible versions with Flutter 3.16.5
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  
  # State Management
  flutter_riverpod: ^2.5.1 # تم استبدال provider بـ flutter_riverpod
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Audio Recording & Playing
  record: ^5.0.4
  audioplayers: ^5.2.1
  permission_handler: ^11.1.0
  
  # Image Handling
  image_picker: ^1.0.7
  image: ^4.1.3
  
  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Ads
  google_mobile_ads: ^4.0.0
  
  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  uuid: ^4.2.2
  
  # HTTP & Networking
  http: ^1.1.2
  
  # Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
    - assets/fonts/
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
